apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
    scrape_configs:

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config
  selfLink: /api/v1/namespaces/default/configmaps/prometheus-config
