apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-deployment
  name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: NodePort
